pipeline {
    agent any
    
    stages {
        stage('Deploy Stage'){
            steps {
                sh '''
                docker rmi $(docker images -q)
                echo "aashish "
                docker run --name some-nginx -d -p 80:80 nginx
                '''
            }
        }
    }
}