pipeline {
    agent any
    
    stages {
        stage('Deploy Stage'){
            steps {
                sh '''
                docker rm $(docker ps -aq)
                echo "aashish"
                docker run --name some-nginx -d -p 80:80 nginx
                '''
            }
        }
    }
}