pipeline {
    agent any
    
    stages {
        stage('Deploy Stage'){
            steps {
                sh "sudo /usr/bin/docker run --name some-nginx -d -p 8080:80 nginx"
            }
        }
    }
}