apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 6
  #revisionHistoryLimit: 3
  stratergy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      #- image: gcr.io/heptio-images/ks-guestbook-demo:0.2
      - image: nginx
        name: guestbook-ui
        ports:
        - containerPort: 80